name: Deploy my CloudFormation stack to dev

on:
  push:
    branches:
      - main # only execute this workflow when I’m pushing to “staging”
  pull_request:
    branches:
      - main
  workflow_dispatch:
    inputs:
      environment:
        description: 'Environment'
        type: string
        options:
        - prod
env:
  AWS_ROLE: arn:aws:iam::343397212430:role/GitHub-Actions-Role
  AWS_REGION: us-west-2
  DEPLOY_ENV: ${{ github.event.inputs.environment || 'dev' }}
  
jobs:
  deploy:
    runs-on: ubuntu-latest
    # Permissions are needed to interact with GitHub's OIDC Token endpoint.
    permissions:
      id-token: write
      contents: read

    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - name: Checkout code from master branch
        uses: actions/checkout@v2

      # Configure AWS Credential
      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          role-to-assume: ${{ env.AWS_ROLE }}
          aws-region: ${{ env.AWS_REGION }}

      # Deploy VPC
      - name: Deploys my VPC
        uses: aws-actions/aws-cloudformation-github-deploy@v1
        with:
          name: ${{ env.DEPLOY_ENV }}-vpc
          template: ./networking.yml
          parameter-overrides: EnvironmentName=${{ env.DEPLOY_ENV }}
